name: chi-course-2019
channels:
  - conda-forge
  - akode
  - kgullikson
dependencies:
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pandas
  - gpy
  - gpyopt
  - scikit-learn
  - gym
  