name: chi-course-2019
channels:
  - conda-forge
  - kgullikson
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - pandas
  - scikit-learn
  - pip
  - pip:
    - gpy
    - gpyopt
    - gym
    
  